# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leecaden/QF633/deribit-vol-surface

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leecaden/QF633/deribit-vol-surface

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leecaden/QF633/deribit-vol-surface/CMakeFiles /home/leecaden/QF633/deribit-vol-surface//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leecaden/QF633/deribit-vol-surface/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CsvFeeder

# Build rule for target.
CsvFeeder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CsvFeeder
.PHONY : CsvFeeder

# fast build rule for target.
CsvFeeder/fast:
	$(MAKE) $(MAKESILENT) -f project/CMakeFiles/CsvFeeder.dir/build.make project/CMakeFiles/CsvFeeder.dir/build
.PHONY : CsvFeeder/fast

#=============================================================================
# Target rules for targets named Msg

# Build rule for target.
Msg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Msg
.PHONY : Msg

# fast build rule for target.
Msg/fast:
	$(MAKE) $(MAKESILENT) -f project/CMakeFiles/Msg.dir/build.make project/CMakeFiles/Msg.dir/build
.PHONY : Msg/fast

#=============================================================================
# Target rules for targets named Date

# Build rule for target.
Date: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Date
.PHONY : Date

# fast build rule for target.
Date/fast:
	$(MAKE) $(MAKESILENT) -f project/CMakeFiles/Date.dir/build.make project/CMakeFiles/Date.dir/build
.PHONY : Date/fast

#=============================================================================
# Target rules for targets named step1

# Build rule for target.
step1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 step1
.PHONY : step1

# fast build rule for target.
step1/fast:
	$(MAKE) $(MAKESILENT) -f project/CMakeFiles/step1.dir/build.make project/CMakeFiles/step1.dir/build
.PHONY : step1/fast

#=============================================================================
# Target rules for targets named step2

# Build rule for target.
step2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 step2
.PHONY : step2

# fast build rule for target.
step2/fast:
	$(MAKE) $(MAKESILENT) -f project/CMakeFiles/step2.dir/build.make project/CMakeFiles/step2.dir/build
.PHONY : step2/fast

#=============================================================================
# Target rules for targets named step3

# Build rule for target.
step3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 step3
.PHONY : step3

# fast build rule for target.
step3/fast:
	$(MAKE) $(MAKESILENT) -f project/CMakeFiles/step3.dir/build.make project/CMakeFiles/step3.dir/build
.PHONY : step3/fast

#=============================================================================
# Target rules for targets named unittestsGradientMaker

# Build rule for target.
unittestsGradientMaker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unittestsGradientMaker
.PHONY : unittestsGradientMaker

# fast build rule for target.
unittestsGradientMaker/fast:
	$(MAKE) $(MAKESILENT) -f project/CMakeFiles/unittestsGradientMaker.dir/build.make project/CMakeFiles/unittestsGradientMaker.dir/build
.PHONY : unittestsGradientMaker/fast

#=============================================================================
# Target rules for targets named test_lbfgs

# Build rule for target.
test_lbfgs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lbfgs
.PHONY : test_lbfgs

# fast build rule for target.
test_lbfgs/fast:
	$(MAKE) $(MAKESILENT) -f project/Solver/LBFGSpp/examples/CMakeFiles/test_lbfgs.dir/build.make project/Solver/LBFGSpp/examples/CMakeFiles/test_lbfgs.dir/build
.PHONY : test_lbfgs/fast

#=============================================================================
# Target rules for targets named test_lbfgs_2

# Build rule for target.
test_lbfgs_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lbfgs_2
.PHONY : test_lbfgs_2

# fast build rule for target.
test_lbfgs_2/fast:
	$(MAKE) $(MAKESILENT) -f project/Solver/LBFGSpp/examples/CMakeFiles/test_lbfgs_2.dir/build.make project/Solver/LBFGSpp/examples/CMakeFiles/test_lbfgs_2.dir/build
.PHONY : test_lbfgs_2/fast

#=============================================================================
# Target rules for targets named test_lbfgs_3

# Build rule for target.
test_lbfgs_3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lbfgs_3
.PHONY : test_lbfgs_3

# fast build rule for target.
test_lbfgs_3/fast:
	$(MAKE) $(MAKESILENT) -f project/Solver/LBFGSpp/examples/CMakeFiles/test_lbfgs_3.dir/build.make project/Solver/LBFGSpp/examples/CMakeFiles/test_lbfgs_3.dir/build
.PHONY : test_lbfgs_3/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CsvFeeder"
	@echo "... Date"
	@echo "... Msg"
	@echo "... step1"
	@echo "... step2"
	@echo "... step3"
	@echo "... test_lbfgs"
	@echo "... test_lbfgs_2"
	@echo "... test_lbfgs_3"
	@echo "... unittestsGradientMaker"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

